version: "3.8"
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
      - LAMBDA_EXECUTOR=docker
        #      - LAMBDA_DOCKER_NETWORK=bridge
      - LOCALSTACK_HOSTNAME=localstack
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
